server:
  port: 8083
  servlet:
    context-path: /employee-service

spring:
  application:
    name: employee-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/